[package]
name = "algebra"
version = { workspace = true }
edition = { workspace = true }

# Optional: Add a description, authors, license, etc.
description = ""
authors = [""]
license = "MIT OR Apache-2.0"

[dependencies]
rand = { workspace = true }